#!/usr/bin/env bash
frontend farah_fronend_https
        bind *:80
        bind *:443 ssl crt /etc/haproxy/certs/www.farahrahali.tech.pem
        redirect scheme https code 301 if !{ ssl_fc }
        default_backend farah_backend

backend farah_backend
        balance roundrobin
        server 378743-web-01 54.146.56.232:80 check
        server 378743-web-02 34.207.58.85:80 check
